# Generated by Django 4.2.21 on 2026-04-10 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_camplocation_applicationform_preferred_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_hi', models.CharField(blank=True, max_length=300, verbose_name='Title (Hindi)')),
                ('description', models.TextField(blank=True)),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dynamic Application Form',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicApplicationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.dynamicapplicationform')),
                ('preferred_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_applicants', to='core.camplocation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dynamic_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Response',
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'form')},
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_text_hi', models.TextField(blank=True, verbose_name='Question (Hindi)')),
                ('question_type', models.CharField(choices=[('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text / Paragraph'), ('SINGLE', 'Single Choice (Radio)'), ('MULTIPLE', 'Multiple Choice (Checkbox)'), ('DROPDOWN', 'Dropdown Select'), ('DATE', 'Date'), ('FILE', 'File Upload'), ('BLANK', 'Fill in the Blank')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('has_other_option', models.BooleanField(default=False, help_text="Add an 'Other' option that reveals a text box when selected")),
                ('placeholder', models.CharField(blank=True, max_length=300)),
                ('placeholder_hi', models.CharField(blank=True, max_length=300, verbose_name='Placeholder (Hindi)')),
                ('help_text', models.TextField(blank=True)),
                ('help_text_hi', models.TextField(blank=True, verbose_name='Help Text (Hindi)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Form Question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=300)),
                ('option_text_hi', models.CharField(blank=True, max_length=300, verbose_name='Option (Hindi)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.formquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_hi', models.CharField(blank=True, max_length=300, verbose_name='Title (Hindi)')),
                ('description', models.TextField(blank=True)),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.dynamicapplicationform')),
            ],
            options={
                'verbose_name': 'Form Section',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='formquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.formsection'),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True)),
                ('other_text', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.dynamicapplicationresponse')),
                ('selected_options', models.ManyToManyField(blank=True, to='core.questionoption')),
            ],
            options={
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('current_section', models.PositiveIntegerField(default=0)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='core.dynamicapplicationform')),
                ('preferred_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camplocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Draft',
                'unique_together': {('user', 'form')},
            },
        ),
    ]
