# Generated by Django 4.2.21 on 2026-04-10 07:16

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dynamicapplicationform_dynamicapplicationresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdraft',
            name='data',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dynamicapplicationresponse',
            name='data',
            field=django_jsonfield_backport.models.JSONField(default=dict),
        ),
    ]
