# Generated by Django 4.2.21 on 2026-04-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_applicationdraft_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdraft',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='dynamicapplicationresponse',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
