# Generated by Django 4.2.21 on 2026-04-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_applicationdraft_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicapplicationform',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='dynamicapplicationresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dynamicapplicationresponse',
            name='form',
        ),
        migrations.RemoveField(
            model_name='dynamicapplicationresponse',
            name='preferred_location',
        ),
        migrations.RemoveField(
            model_name='dynamicapplicationresponse',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='dynamicapplicationresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='section',
        ),
        migrations.RemoveField(
            model_name='formsection',
            name='form',
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='response',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.DeleteModel(
            name='ApplicationDraft',
        ),
        migrations.DeleteModel(
            name='DynamicApplicationForm',
        ),
        migrations.DeleteModel(
            name='DynamicApplicationResponse',
        ),
        migrations.DeleteModel(
            name='FormQuestion',
        ),
        migrations.DeleteModel(
            name='FormSection',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
