# Generated by Django 4.2.21 on 2026-04-11 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_dynamicapplicationform_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField(verbose_name='Question (English)')),
                ('question_hi', models.TextField(verbose_name='Question (Hindi)')),
                ('hint_en', models.CharField(blank=True, max_length=500, verbose_name='Hint (English)')),
                ('hint_hi', models.CharField(blank=True, max_length=500, verbose_name='Hint (Hindi)')),
                ('question_type', models.CharField(choices=[('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text / Subjective'), ('SINGLE', 'Single Choice (Radio)'), ('MULTI', 'Multiple Choice (Checkboxes)'), ('SELECT', 'Dropdown Select'), ('DATE', 'Date Picker'), ('NUMBER', 'Number Input'), ('EMAIL', 'Email Input'), ('PHONE', 'Phone Number')], default='TEXTAREA', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Question',
                'verbose_name_plural': 'Form Questions',
                'ordering': ['section__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300, verbose_name='Title (English)')),
                ('title_hi', models.CharField(max_length=300, verbose_name='Title (Hindi)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_hi', models.TextField(blank=True, verbose_name='Description (Hindi)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_en', models.CharField(max_length=500, verbose_name='Option Text (English)')),
                ('option_hi', models.CharField(max_length=500, verbose_name='Option Text (Hindi)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_other', models.BooleanField(default=False, help_text="Tick to make this the 'Other — please specify' option")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.formquestion')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='formquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.formsection'),
        ),
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=2)),
                ('_answers', models.TextField(blank=True, db_column='answers', default='{}')),
                ('last_step', models.PositiveIntegerField(default=0)),
                ('last_saved', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camplocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_draft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('_selected_options', models.TextField(blank=True, db_column='selected_options', default='[]')),
                ('other_text', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.applicationform')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.formquestion')),
            ],
            options={
                'ordering': ['question__section__order', 'question__order'],
                'unique_together': {('application', 'question')},
            },
        ),
    ]
